#!/bin/sh

hugo
rm -r public/sitemap.xml public/index.xml public/categories.html public/categories public/posts.html public/tags public/tags.html
mv public/404.html public/not_found.html
neocities push public
